name: "MPC Energy"
description: "Test App"
version: "0.0.1"
slug: "mpc_energy"
init: false
arch:
  - amd64

hassio_api: true

ingress: true
ingress_port: 8501

panel_icon: mdi:chart-line

map:
  - type: addon_config
    read_only: false

startup: services


options:
  log_level: info
  ha_api_key: ""
  ha_mqtt_user: ""
  ha_mqtt_pass: ""
  amber_api_key: ""
  amber_site_id: ""
  battery_discharge_cost: 7
  ha_ems_control_switch_entity_id: ""
  ems_control_mode_entity_id: ""
  battery_discharge_limiter_entity_id: ""
  battery_charge_limiter_entity_id: ""
  pv_limiter_entity_id: ""
  export_limiter_entity_id: ""
  import_limiter_entity_id: ""
  battery_rated_capacity_entity_id: ""
  backup_soc_entity_id: ""
  charge_cutoff_soc_entity_id: ""
  battery_max_charge_power_limit_entity_id: ""
  battery_max_discharge_power_limit_entity_id: ""
  pv_max_power_limit_entity_id: ""
  import_max_power_limit_entity_id: ""
  export_max_power_limit_entity_id: ""
  load_power_entity_id: ""
  solar_power_entity_id: ""
  battery_power_entity_id: ""
  inverter_power_entity_id: ""
  grid_power_entity_id: ""
  solcast_forecast_entity_id: ""


schema:
  log_level: list(debug|info|warning|error|critical)
  ha_api_key: str
  ha_mqtt_user: str
  ha_mqtt_pass: str
  amber_api_key: password
  amber_site_id: str?
  battery_discharge_cost: int?
  ha_ems_control_switch_entity_id: str
  ems_control_mode_entity_id: str
  battery_discharge_limiter_entity_id: str
  battery_charge_limiter_entity_id: str
  pv_limiter_entity_id: str
  export_limiter_entity_id: str
  import_limiter_entity_id: str
  battery_rated_capacity_entity_id: str
  backup_soc_entity_id: str
  charge_cutoff_soc_entity_id: str
  battery_max_charge_power_limit_entity_id: str
  battery_max_discharge_power_limit_entity_id: str
  pv_max_power_limit_entity_id: str
  import_max_power_limit_entity_id: str
  export_max_power_limit_entity_id: str
  load_power_entity_id: str
  solar_power_entity_id: str
  battery_power_entity_id: str
  inverter_power_entity_id: str
  grid_power_entity_id: str
  solcast_forecast_entity_id: str


