name: "MPC Energy"
description: "Test App"
version: "0.0.1"
slug: "mpc_energy"
init: false
arch:
  - amd64

hassio_api: true

ingress: true
ingress_port: 8501

panel_icon: mdi:chart-line

map:
  - type: addon_config
    read_only: false

startup: services